options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating .env file with environment variables..."
        cat <<EOF > .env
        APP_URL=$_APP_URL
        DB_DATABASE=$_DB_DATABASE
        DB_HOST=$_DB_HOST
        DB_LOGGING=$_DB_LOGGING
        DB_PASSWORD=$_DB_PASSWORD
        DB_PORT=$_DB_PORT
        DB_SYNC=$_DB_SYNC
        DB_TYPE=$_DB_TYPE
        DB_USERNAME=$_DB_USERNAME
        JWT_SECRET=$_JWT_SECRET
        SLACK_CLIENT_ID=$_SLACK_CLIENT_ID
        SLACK_CLIENT_SECRET=$_SLACK_CLIENT_SECRET
        SLACK_SCOPES=$_SLACK_SCOPES
        SLACK_SIGNING_SECRET=$_SLACK_SIGNING_SECRET
        SLACK_STATE_SECRET=$_SLACK_STATE_SECRET
        EOF
        echo ".env file created."
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'ENV_FILE=.env', '-t', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/vacaybuddy-registry/vacaybuddy-image:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/vacaybuddy-registry/vacaybuddy-image:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'vacaybuddy-server'
      - '--image=asia-northeast3-docker.pkg.dev/$PROJECT_ID/vacaybuddy-registry/vacaybuddy-image:$SHORT_SHA'
      - '--region=asia-northeast3'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--project=$PROJECT_ID'